### PR TITLE
Add support for old safe send link format

### LINKED ISSUE #24: Support old requestLink generated from the donation app / safe
Currently the wallet doesn't support the old requestLink format used in the safe & in the donation app.
The donation app will be updated to generate new requestLink for the wallet, but we should still support old ones.

### PR DESCRIPTION
**Pull request by mariofriz**
This PR fixes #24 

Changes:
- Add a route watcher, that transforms old format to new format

Tasks:
- [x] Add support for address + amount
- [x] Add support for address only

### CODE REVIEW

**Comment by sisou** [comment]
I don't know how this happened, but this PR now includes unrelated Portuguese translations. Can you maybe rebase this on top of `master` with only the relevant commits?

**Comment by mariofriz** [comment]
> I don't know how this happened, but this PR now includes unrelated Portuguese translations. Can you maybe rebase this on top of `master` with only the relevant commits?

Indeed something weird happened I had a strange error while rebasing, I ended up skipping the problematic commit. I rebased onto master now and also changed to named regex groups so it's a bit easier to read.

**Comment by mariofriz** [comment]
@sisou Hi, I know you are busy with Nimiq 2.0 but if you get a quick chance to review this PR that would be great! If changes are needed, please let me know.

**Comment by sisou** [comment]
Thank you very much @mariofriz! :+1:

**Pull request merged**
